[package]
name = "rusgit"
version = "0.1.0"
authors = ["terassyi <iscale821@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
libflate = "0.1.27"
chrono = "0.4.0"
hex = "0.3.1"
